# Generated by Django 6.0 on 2025-12-05 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='date_added',
            field=models.DateField(default=datetime.date(2025, 12, 5)),
        ),
    ]
