# Generated by Django 6.0 on 2025-12-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_resource_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date_added',
            field=models.DateField(),
        ),
    ]
