# Generated by Django 6.0 on 2025-12-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_keyword_keyword_alter_resource_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='aspect_ratio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='audio_quality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='video_quality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
